package config

const (
	GLOBAL_DB_NAME = "ggac"
	GLOBAL_DB_USERNAME = "root"
	GLOBAL_DB_PASSWORD = "Hello.123"
	GLOBAL_DB_HOST = "192.168.64.146"
	GLOBAL_DB_PORT = "3328"
	GLOBAL_DB_CHARSET = "utf8mb4"
	GLOBAL_DB_DIRVER = "mysql"
)